# Đọc file secret dùng chung với macOS/Linux. Nguồn là cú pháp shell
# (`export K="V"`) vì đó là thứ zsh source trực tiếp; ở đây `export` chỉ là
# tiền tố tuỳ chọn cần bỏ qua.
#
# Value được coi là chữ thuần: không nội suy `$`, backtick hay `$(...)`. Luật đó
# ghi ở CLAUDE.md. Sinh ra chuỗi nháy đơn của PowerShell nên kể cả khi luật bị
# vi phạm cũng không có gì được thực thi.
function ConvertFrom-ShellEnv {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$Text
    )

    $pairs = [ordered]@{}

    foreach ($line in ($Text -split "`r?`n")) {
        $trimmed = $line.Trim()
        if ($trimmed -eq '')            { continue }
        if ($trimmed.StartsWith('#'))   { continue }
        if ($trimmed -notmatch '^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$') { continue }

        $name  = $Matches[1]
        $value = $Matches[2].Trim()

        # Chỉ bỏ đúng một cặp nháy bọc ngoài. Nháy bên trong là dữ liệu.
        if ($value.Length -ge 2) {
            $first = $value[0]
            $last  = $value[$value.Length - 1]
            if (($first -eq '"' -and $last -eq '"') -or ($first -eq "'" -and $last -eq "'")) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }

        $pairs[$name] = $value
    }

    return $pairs
}

# Ghi qua temp rồi move, giống hệt `agenix-reload` trên Unix và vì cùng lý do:
# một lần ghi hỏng không được để lại file cụt. ACL đặt trên temp *trước* khi
# move, nên không có khoảnh khắc nào file đích tồn tại với quyền kế thừa.
function Write-PwshSecretsFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Pairs,
        [Parameter(Mandatory)][string]$Path
    )

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    $lines = @('# Generated by windows/lib/Secrets.psm1 -- do not edit, do not commit.')
    foreach ($name in $Pairs.Keys) {
        $escaped = [string]$Pairs[$name] -replace "'", "''"
        $lines  += ('$env:{0} = ''{1}''' -f $name, $escaped)
    }

    $tmp = Join-Path $dir ('.tmp.' + [System.IO.Path]::GetRandomFileName())
    try {
        Set-Content -LiteralPath $tmp -Value $lines -Encoding UTF8 -Force

        $me = [Security.Principal.WindowsIdentity]::GetCurrent().Name
        & icacls $tmp /inheritance:r /grant:r "${me}:(R,W)" | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "icacls failed on $tmp" }

        Move-Item -LiteralPath $tmp -Destination $Path -Force
    }
    finally {
        if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force }
    }

    return $Pairs.Count
}

Export-ModuleMember -Function ConvertFrom-ShellEnv, Write-PwshSecretsFile
