# Đọc file secret dùng chung với macOS/Linux. Nguồn là cú pháp shell
# (`export K="V"`) vì đó là thứ zsh source trực tiếp; ở đây `export` chỉ là
# tiền tố tuỳ chọn cần bỏ qua.
#
# Value được coi là chữ thuần: không nội suy `$`, backtick hay `$(...)`. Luật đó
# ghi ở CLAUDE.md. Sinh ra chuỗi nháy đơn của PowerShell nên kể cả khi luật bị
# vi phạm cũng không có gì được thực thi.
function ConvertFrom-ShellEnv {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$Text
    )

    $pairs = [ordered]@{}

    foreach ($line in ($Text -split "`r?`n")) {
        $trimmed = $line.Trim()
        if ($trimmed -eq '')            { continue }
        if ($trimmed.StartsWith('#'))   { continue }
        if ($trimmed -notmatch '^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$') { continue }

        $name  = $Matches[1]
        $value = $Matches[2].Trim()

        # Chỉ bỏ đúng một cặp nháy bọc ngoài. Nháy bên trong là dữ liệu.
        if ($value.Length -ge 2) {
            $first = $value[0]
            $last  = $value[$value.Length - 1]
            if (($first -eq '"' -and $last -eq '"') -or ($first -eq "'" -and $last -eq "'")) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }

        $pairs[$name] = $value
    }

    return $pairs
}

# Ghi qua temp rồi thay thế đích, giống hệt `agenix-reload` trên Unix và vì
# cùng lý do: một lần ghi hỏng không được để lại file cụt, và không được xoá
# mất bản cũ. ACL đặt trên temp *trước* khi thay thế, nên không có khoảnh
# khắc nào file đích tồn tại với quyền kế thừa.
#
# KHÔNG dùng `Move-Item -Force`: khi đích đã tồn tại, PowerShell xoá đích rồi
# mới move lại (không atomic), và nếu lần move lại đó thất bại -- AV hay
# search indexer giữ khoá tạm thời, chuyện thường trên Windows -- lỗi chỉ là
# non-terminating (WriteError). Hệ quả: file cũ đã mất, file mới chưa tới,
# không gì throw, và hàm vẫn trả về như đã ghi xong. Đó chính xác là điều
# thiết kế temp+move tồn tại để ngăn.
#
# Dùng [System.IO.File]::Replace khi đích đã có: atomic thật (ReplaceFile
# của Win32), sẵn trên .NET Framework 4.x -- khác overload 3 tham số của
# File.Move, cái đó chỉ có từ .NET Core 3.0, không chạy được trên Windows
# PowerShell 5.1. Lần ghi đầu tiên (đích chưa tồn tại) dùng File.Move hai
# tham số: không có gì để thay thế, nhưng cũng không có gì để mất. Cả hai
# ném exception .NET thật (terminating, không phụ thuộc $ErrorActionPreference
# của caller) khi thất bại, nên `return` phía dưới không bao giờ chạy trên
# đường thất bại.
#
# Tham số backup của Replace KHÔNG được truyền $null trần: một $null trần
# marshal thành chuỗi rỗng khi bind vào tham số String của method .NET, và
# File.Replace ném "The path is not of a legal form" vì "" không phải path
# hợp lệ (không phải vì thiếu [NullString] -- kiểu đó có từ PowerShell 3.0,
# kể cả trên Windows PowerShell 5.1). [NullString]::Value tồn tại đúng để
# đi qua tình huống này: ép PowerShell truyền một null reference thật cho
# tham số String thay vì "". Không tạo backup -> không có gì phải dọn, và
# vì thế không có nguy cơ một file backup chứa secret cũ nằm lại vô thời
# hạn nếu bước dọn tự nó thất bại (AV/indexer giữ khoá tạm thời).
function Write-PwshSecretsFile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][System.Collections.IDictionary]$Pairs,
        [Parameter(Mandatory)][string]$Path
    )

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    $lines = @('# Generated by windows/lib/Secrets.psm1 -- do not edit, do not commit.')
    foreach ($name in $Pairs.Keys) {
        $escaped = [string]$Pairs[$name] -replace "'", "''"
        $lines  += ('$env:{0} = ''{1}''' -f $name, $escaped)
    }

    $tmp = Join-Path $dir ('.tmp.' + [System.IO.Path]::GetRandomFileName())
    try {
        Set-Content -LiteralPath $tmp -Value $lines -Encoding UTF8 -Force -ErrorAction Stop

        $me = [Security.Principal.WindowsIdentity]::GetCurrent().Name
        & icacls $tmp /inheritance:r /grant:r "${me}:(R,W)" | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "icacls failed on $tmp" }

        if (Test-Path -LiteralPath $Path) {
            [System.IO.File]::Replace($tmp, $Path, [NullString]::Value)
        } else {
            [System.IO.File]::Move($tmp, $Path)
        }
    }
    finally {
        if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue }
    }

    return $Pairs.Count
}

Export-ModuleMember -Function ConvertFrom-ShellEnv, Write-PwshSecretsFile
