git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
customCommands:
  - key: "D"
    context: "commits"
    command: "git diff {{.SelectedLocalCommit.Sha}}^ {{.SelectedLocalCommit.Sha}} | diffnav"
    output: terminal
  - key: "D"
    context: "files"
    command: "git diff | diffnav"
    output: terminal
  - key: "D"
    context: "localBranches"
    command: "git diff {{.SelectedLocalBranch.Name}} | diffnav"
    output: terminal
