#!/bin/bash

APP_NAME="$1"

LOCK_NAME=$(echo "$APP_NAME" | sed 's/[^a-zA-Z0-9]/_/g')
LOCK_FILE="/tmp/toggle_app_${LOCK_NAME}.lock"

exec 9>"$LOCK_FILE"

if ! flock -n 9; then
  exit 0
fi

FOCUSED_APP_NAME=$(aerospace list-windows --focused --json | jq -r '.[0]."app-name"' 2>/dev/null)
# Get the first window ID of the app
WINDOW_ID=$(aerospace list-windows --json --all | jq --raw-output --arg app_name_filter "$APP_NAME" '.[] | select(."app-name" == $app_name_filter) | ."window-id"' | head -n 1 2>/dev/null)
FOCUSED_WS=$(aerospace list-workspaces --focused)

if [ "$APP_NAME" = "$FOCUSED_APP_NAME" ]; then
  # Very slow to hide using AppleScript
  # osascript -e 'tell application "System Events" to keystroke "h" using {command down}'
  aerospace move-node-to-workspace 0
elif [ -n "$WINDOW_ID" ]; then
  # Replace app if more than 2 apps
  # if [ $(aerospace list-windows --workspace v --count) -gt 1 ]; then
  #   aerospace move-node-to-workspace 0
  # fi
  # Bug: sometimes the window is already on the focused workspace but not focused
  aerospace move-node-to-workspace "$FOCUSED_WS" --window-id $WINDOW_ID --focus-follows-window --fail-if-noop || open -a "$APP_NAME"
else
  open -a "$APP_NAME"
fi

