#!/bin/bash

APP_NAME="$1"

IS_FRONTMOST=$(osascript -e "
    try
        tell application \"$APP_NAME\" to return its frontmost
    on error
        return false
    end try
" 2>/dev/null)

if [ "$IS_FRONTMOST" = "true" ]; then
    osascript -e 'tell application "System Events" to keystroke "h" using {command down}'
else
    FOCUSED_WS=$(aerospace list-workspaces --focused)
    open -a "$APP_NAME"
    aerospace move-node-to-workspace "$FOCUSED_WS" --focus-follows-window
fi