#!/bin/bash

APP_NAME="$1"

osascript -e "
    set AppName to \"$APP_NAME\"
    
    tell application AppName
        if it is running then
            if it is frontmost then
                tell application \"System Events\"
                    click menu item (\"Hide \" & AppName) of menu AppName of menu bar 1 of process AppName
                end tell
            else
                activate
            end if
        else
            launch
        end if
    end tell
"