#!/bin/bash

APP_NAME="$1"

osascript -e "
    set AppName to \"$APP_NAME\"
    
    tell application AppName
        if it is frontmost then
            do shell script \"aerospace workspace-back-and-forth\"
        else
            do shell script \"open -a '\" & AppName & \"'\"
        end if
    end tell
"