#!/bin/bash

APP_NAME="$1"

LOCK_NAME=$(echo "$APP_NAME" | sed 's/[^a-zA-Z0-9]/_/g')
LOCK_FILE="/tmp/toggle_app_${LOCK_NAME}.lock"

exec 9>"$LOCK_FILE"

if ! flock -n 9; then
  exit 0
fi

IS_FRONTMOST=$(osascript -e "
    try
        tell application \"$APP_NAME\" to return its frontmost
    on error
        return false
    end try
" 2>/dev/null)

# Get the first window ID of the app
WINDOW_ID=$(aerospace list-windows --json --all | jq --raw-output --arg app_name_filter "$APP_NAME" '.[] | select(."app-name" == $app_name_filter) | ."window-id"' | head -n 1 2>/dev/null)
FOCUSED_WS=$(aerospace list-workspaces --focused)

if [ "$IS_FRONTMOST" = "true" ]; then
  hs -c 'local window = hs.window.focusedWindow(); if window then window:application():hide() end'
  echo "Hide $APP_NAME"
else
  if [ -n "$WINDOW_ID" ]; then
    # Bug: sometimes the window is already on the focused workspace but not focused
    aerospace move-node-to-workspace "$FOCUSED_WS" --window-id $WINDOW_ID --focus-follows-window --fail-if-noop || open -a "$APP_NAME"
    echo "Focused $APP_NAME"
  else
    open -a "$APP_NAME"
    echo "Opened $APP_NAME"
  fi
fi

