#!/bin/bash

APP_NAME="$1"

IS_FRONTMOST=$(osascript -e "
    try
        tell application \"$APP_NAME\" to return its frontmost
    on error
        return false
    end try
" 2>/dev/null)

if [ "$IS_FRONTMOST" = "true" ]; then
    aerospace workspace-back-and-forth
else
    open -a "$APP_NAME"
    # aerospace move-node-to-workspace "$APP_NAME" --focus-follows-window
fi