---
- name: Ubuntu Install
  hosts: local
  become: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_env.SUDO_USER }}"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.SUDO_USER }}"
  tasks:

    # --- Install apt packages ---
    - name: Install individual apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: yes
      loop:
        - tailscale
