#cloud-config
autoinstall:
  version: 1

  locale: en_US.UTF-8 # Ngôn ngữ và mã hóa

  keyboard:
    layout: us # Bố cục bàn phím
    variant: ''

  timezone: Asia/Ho_Chi_Minh # Múi giờ, ví dụ: 'Asia/Ho_Chi_Minh' hoặc 'America/New_York'

  early-commands:
    - systemctl stop ssh
    - hostnamectl set-hostname ubuntu-00
    - dhclient

  network:
    version: 2
    ethernets:
      eth0:
        dhcp4: yes

  ssh:
    install-server: yes

  identity:
    hostname: kln
    password: $6$jCfWFbdxh1lK09sY$pxFnrW/yXewYFmgoaywu3WKhdPQg0e8DR8jvedAV.udXM0.i5M6wr4Up2S7ZCN9kNDmg.s7fmrOaXE6nEyzPb/
    username: ubuntu

  storage:
    layout:
      name: lvm

  packages:
    - open-vm-tools
    - ansible
    - git

  user-data:
    disable_root: false

  late-commands:
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/sysuser
    - sed -ie 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"/' /target/etc/default/grub
    - curtin in-target --target /target update-grub2