# Lockscreen
bindsym $mod+$alt+l exec swaylock

# Exit sway session
bindsym $mod+$alt+Shift+l exec "zenity --question --text='Exit sway session?' --title='Confirmation' && swaymsg exit"

# Reboot
bindsym $mod+$alt+Shift+r exec "zenity --question --text='Reboot the system?' --title='Confirmation' && systemctl reboot"

# Shutdown
bindsym $mod+$alt+Shift+s exec "zenity --question --text='Shutdown the system?' --title='Confirmation' && systemctl poweroff"

# Hibernate
bindsym $mod+$alt+Shift+h exec "zenity --question --text='Hibernate the system?' --title='Confirmation' && systemctl hibernate"
