# idle management: lock after 5min, screen off after 10min, lock before sleep
exec swayidle -w \
    timeout 300 'swaylock -f' \
    timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
    before-sleep 'swaylock -f'

# lid switch: suspend when closing lid
bindswitch --reload --locked lid:on exec systemctl suspend

# Lockscreen
bindsym $mod+$alt+l exec swaylock

# Exit sway session
bindsym $mod+$alt+Shift+l exec "echo -e 'Yes\nNo' | rofi -dmenu -p 'Exit sway session?' | grep -q Yes && swaymsg exit"

# Reboot
bindsym $mod+$alt+Shift+r exec "echo -e 'Yes\nNo' | rofi -dmenu -p 'Reboot the system?' | grep -q Yes && systemctl reboot"

# Shutdown
bindsym $mod+$alt+Shift+s exec "echo -e 'Yes\nNo' | rofi -dmenu -p 'Shutdown the system?' | grep -q Yes && systemctl poweroff"

# Hibernate
bindsym $mod+$alt+Shift+h exec "echo -e 'Yes\nNo' | rofi -dmenu -p 'Hibernate the system?' | grep -q Yes && systemctl hibernate"
