# Battery
bindsym $tab+p exec notify-send -t 2000 "$(upower -i /org/freedesktop/UPower/devices/battery_qcom_battmgr_bat | awk '/state:/{s=$2} /percentage:/{p=$2} /energy-rate:/{w=$2} END{printf "%s %s %.1fW", s, p, w}')"

# Time
bindsym $tab+t exec notify-send -t 2000 "$(date +'%H:%M:%S - %d/%m/%Y')"

# Reload
bindsym $tab+r exec swaymsg reload && notify-send -t 2000 "Sway config reloaded"

# Screenshot (grim + slurp)
set $screenshot exec grim -g "$(slurp)" /tmp/screenshot.png && echo -n /tmp/screenshot.png | wl-copy && wl-copy < /tmp/screenshot.png && notify-send -t 2000 "Screenshot copied to clipboard"
bindsym Print $screenshot
bindsym $tab+s $screenshot
