include theme.conf

background_opacity 0.85
dynamic_background_opacity yes
allow_remote_control yes
confirm_os_window_close 0
enable_blur true
remember_window_size  yes
tab_bar_style separator
include current-theme.conf
macos_option_as_alt yes

map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

map super+v paste_from_clipboard
map super+c copy_or_interrupt

kitty_mod ctrl+shift
map kitty_mod+r load_config_file

font_family family="DejaVuSansMono"
font_size 18.0

hide_window_decorations yes
term xterm-256color
tab_separator       "|"
tab_title_template  " {index} {title} "
tab_bar_edge top
# tab_bar_style hidden
map ctrl+shift+p>n new_window

