include theme.conf

background_opacity 0.85
dynamic_background_opacity yes
allow_remote_control yes
clipboard_control write-clipboard write-primary read-clipboard read-primary
confirm_os_window_close 0
enable_blur true
remember_window_size  yes
tab_bar_style separator
include current-theme.conf
macos_option_as_alt yes

map super+v paste_from_clipboard
map super+c copy_or_interrupt

font_family family="DejaVuSansMono"
font_size 18.0

hide_window_decorations yes
term xterm-256color
tab_separator       "|"
tab_title_template  " {index} {title} "
tab_bar_edge top
# tab_bar_style hidden

kitty_mod ctrl+shift
map kitty_mod+5 load_config_file

map kitty_mod+h previous_tab
map kitty_mod+l next_tab
# map ctrl+shift+p>n launch --type=tab --tab-title "My Tab"

map kitty_mod+1 goto_tab 1
map kitty_mod+2 launch ~/.config/kitty/launcher.sh 2 
map kitty_mod+3 launch ~/.config/kitty/launcher.sh 3 
map kitty_mod+4 launch ~/.config/kitty/launcher.sh 4 
map kitty_mod+r launch ~/.config/kitty/launcher.sh "rog" "ssh rog"
map kitty_mod+m launch ~/.config/kitty/launcher.sh "macmini" "ssh macmini"
# map kitty_mod+n launch ~/.config/kitty/launcher.sh "nix" "tmux attach -t nix"

map kitty_mod+9 set_background_opacity 1.0
map kitty_mod+0 set_background_opacity default

