alias f='fzf'
alias cat='bat --paging=never --plain'
alias fp='fzf --preview="bat --color=always {}"'
alias vf='nvim $(fzf -m --preview="bat --color=always {}")'
alias ls='eza --icons --group-directories-first'
alias lzg='lazygit'
alias v='nvim'
alias vcf='cd ~/.config/nvim && nvim'
alias spy='source .venv/bin/activate'
alias gu='git pull && git add . && git commit -m "update" && git push'
alias lzd='lazydocker'
alias py='python'
alias m='micromamba'
alias mamba='micromamba'
alias nvitop='uvx nvitop'
alias btcli='uvx --from bittensor-cli btcli'
alias rsyncgit='rsync -av --exclude ".git/" --exclude-from=".gitignore"'
