
# linux alt+F2 lg -> insert -> Evaluator -> r(0).get_wm_class_instance()

<Super><Alt><Ctrl>b:minimize-when-unfocused:isolate-workspace,brave,brave-browser,
# <Super><Alt><Ctrl>c:minimize-when-unfocused:isolate-workspace,google-chrome-stable,Google-chrome,
<Super><Alt><Ctrl><Shift>f:minimize-when-unfocused:isolate-workspace,firefox,firefox,

<Super><Alt><Ctrl>f:minimize-when-unfocused:isolate-workspace,nautilus,org.gnome.Nautilus,
<Super><Alt><Ctrl>n:minimize-when-unfocused:isolate-workspace,flatpak run com.simplenote.Simplenote,Simplenote,
<Super><Alt><Ctrl>s:minimize-when-unfocused:isolate-workspace,gnome-control-center,org.gnome.Settings,
<Super><Alt><Ctrl>v:minimize-when-unfocused:isolate-workspace,code,code,
<Super><Alt><Ctrl>t:minimize-when-unfocused:isolate-workspace,kitty,kitty,
<Super><Alt><Ctrl>m:minimize-when-unfocused:isolate-workspace,caprine,,
<Super><Alt><Ctrl>d:minimize-when-unfocused:isolate-workspace,discord,discord,
<Super><Alt><Ctrl><Shift>b:minimize-when-unfocused:isolate-workspace,gnome-boxes,org.gnome.Boxes,
<Super><Alt><Ctrl>x:minimize-when-unfocused:isolate-workspace,Telegram,org.telegram.desktop,
<Super><Alt><Ctrl><Shift>e:minimize-when-unfocused:isolate-workspace,extension-manager,com.mattjakeman.ExtensionManager,

<Super><Alt><Ctrl>g:minimize-when-unfocused:isolate-workspace,brave --app=https://gemini.google.com, gemini.google.com,
<Super><Alt><Ctrl><Shift>m:minimize-when-unfocused:isolate-workspace,brave --app=https://mail.google.com, mail.google.com,
<Super><Alt><Ctrl>k:minimize-when-unfocused:isolate-workspace,brave --app=https://keep.google.com, keep.google.com,
<Super><Alt><Ctrl><Shift>d:minimize-when-unfocused:isolate-workspace,brave --app=https://chat.deepseek.com, chat.deepseek.com,
<Super><Alt><Ctrl>y:minimize-when-unfocused:isolate-workspace,brave --app=https://www.youtube.com, www.youtube.com,
<Super><Alt><Ctrl>q:minimize-when-unfocused:isolate-workspace,qutebrowser,,