bind -n M-o if-shell -F '#{==:#{session_name},obsidian}' 'switch-client -l' 'run-shell "sesh connect obsidian"'
bind -n M-n if-shell -F '#{==:#{session_name},nix}' 'switch-client -l' 'run-shell "sesh connect nix"'
bind -n M-g if-shell -F '#{==:#{session_name},aichat}' 'switch-client -l' 'run-shell "sesh connect aichat"'
bind -n M-m if-shell -F '#{==:#{session_name},main}' 'switch-client -l' 'run-shell "sesh connect main"'

bind -n M-space display-popup -E -h 100% -w 100% "sesh connect \"$(
  sesh list -i | fzf --no-sort --ansi --prompt='⚡ '
)\""
