SS="~/.config/tmux/tmux.d/switch-session.sh"

bind -n M-o run-shell "$SS obsidian ~/Documents/obsidian"
bind -n M-n run-shell "$SS nix ~/.nix"
bind -n M-g run-shell "$SS aichat  ~"
bind -n M-m run-shell "$SS main  ~"
