# Volume control
set $notify-volume notify-send -h string:x-canonical-private-synchronous:vol -t 2000 "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
bindsym XF86AudioRaiseVolume exec wpctl set-volume --limit 2.0 @DEFAULT_AUDIO_SINK@ 10%+ && $notify-volume
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && $notify-volume
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $notify-volume

# Microphone mute
set $notify-mic notify-send -h string:x-canonical-private-synchronous:mic -t 2000 "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"
bindsym XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && $notify-mic

# Brightness control
set $notify-brightness notify-send -h string:x-canonical-private-synchronous:br -t 2000 "$(brightnessctl -m)"
bindsym XF86MonBrightnessUp exec brightnessctl set 10%+ && $notify-brightness
bindsym XF86MonBrightnessDown exec brightnessctl set 10%- && $notify-brightness

# Screenshot (grim + slurp)
bindsym Print exec grim -g "$(slurp)" - | wl-copy
bindsym $tab+grave exec grim -g "$(slurp)" - | wl-copy

# Battery
bindsym $tab+p exec notify-send -t 2000 "$(cat /sys/class/power_supply/qcom-battmgr-bat/status) $(cat /sys/class/power_supply/qcom-battmgr-bat/energy_now | awk '{printf \"%.1f Wh\", $1/1000000}') $(cat /sys/class/power_supply/qcom-battmgr-bat/power_now | awk '{printf \"%.1fW\", -$1/1000000}')"

# Time
bindsym $tab+t exec notify-send -t 2000 "$(date +'%H:%M:%S - %d/%m/%Y')"
