bindsym $mod+Return exec kitty

set $focus exec ~/.config/sway/scripts/sway-focus.sh
set $toggle exec ~/.config/sway/scripts/sway-toggle.sh

# Kitty
bindsym $cap+space $focus "kitty" "kitty"

# Browser
set $browser brave
set $browser_app_id brave-browser

bindsym $cap+b $focus $browser_app_id $browser
# Web Apps
bindsym $cap+g       $focus "gemini.google.com" "$browser --app=https://gemini.google.com"
bindsym $cap+c       $focus "claude.ai__new" "$browser --app=https://claude.ai/new"
bindsym $cap+k       $focus "keep.google.com" "$browser --app=https://keep.google.com"
bindsym $cap+y       $focus "www.youtube.com" "$browser --app=https://www.youtube.com"
bindsym $cap+shift+d $focus "chat.deepseek.com" "$browser --app=https://chat.deepseek.com"
bindsym $cap+shift+m $focus "mail.google.com" "$browser --app=https://mail.google.com/"
bindsym $cap+shift+n $focus "www.notion.so" "$browser --app=https://www.notion.so/"
bindsym $cap+d       $focus "discord.com__app" "$browser --app=https://discord.com/app"
bindsym $cap+m       $focus "www.facebook.com__messages" "$browser --app=https://www.facebook.com/messages"
bindsym $cap+t       $focus "web.telegram.org" "$browser --app=https://web.telegram.org"

focus_on_window_activation focus
