# Lockscreen
bindsym $mod+$alt+l exec swaylock

# Exit sway session
bindsym $mod+$alt+Shift+l exec swaynag -t warning -m 'Exit sway session?' -B 'Yes' 'swaymsg exit'

# Reboot
bindsym $mod+$alt+Shift+r exec swaynag -t warning -m 'Reboot the system?' -B 'Yes' 'systemctl reboot'

# Shutdown
bindsym $mod+$alt+Shift+s exec swaynag -t warning -m 'Shutdown the system?' -B 'Yes' 'systemctl poweroff'

# Hibernate
bindsym $mod+$alt+Shift+h exec swaynag -t warning -m 'Hibernate the system?' -B 'Yes' 'systemctl hibernate'
