# notification
exec dunst

# background
exec_always swaybg -i ~/.nix/home-manager/dotfiles/images/nix-waifu.png -m fill

# clipboard
exec wl-paste --watch cliphist store

# rofi
bindsym $mod+d exec rofi -show drun
bindsym $mod+space exec rofi -show combi
bindsym $alt+Tab exec rofi -show window

exec_always autotiling

# vietnamese input
exec fcitx5 -rd

# keyboard repeat rate and delay
input "type:keyboard" {
    repeat_rate 30
    repeat_delay 200
}
