# notification (mako = native wayland)
exec mako

# background
exec_always swaybg -i ~/.nix/home-manager/dotfiles/images/nix-waifu.png -m fill

# clipboard
exec wl-paste --watch cliphist store

# rofi
bindsym $mod+d exec rofi -normal-window -show drun
bindsym $mod+space exec rofi -normal-window -show combi
bindsym $alt+Tab exec rofi -normal-window -show window

exec_always autotiling

# vietnamese input
exec_always fcitx5 -rd

# keyboard repeat rate and delay
input "type:keyboard" {
    repeat_rate 30
    repeat_delay 200
}

# touchpad
input "type:touchpad" {
    natural_scroll enabled
    tap enabled
    dwt enabled
    scroll_method two_finger
    middle_emulation enabled
}
