# linux alt+F2 lg
<Hyper>b:minimize-when-unfocused:isolate-workspace,brave-browser,brave-browser,
# <Hyper>c:minimize-when-unfocused:isolate-workspace,google-chrome-stable,Google-chrome,
# <Hyper>e:minimize-when-unfocused:isolate-workspace,microsoft-edge,,
# <Super>f:minimize-when-unfocused:isolate-workspace,firefox,,

<Hyper>f:minimize-when-unfocused:isolate-workspace,nautilus,org.gnome.Nautilus,
<Hyper>n:minimize-when-unfocused:isolate-workspace,flatpak run com.simplenote.Simplenote,Simplenote,
<Hyper>j:minimize-when-unfocused:isolate-workspace,joplin-desktop,Joplin,
<Hyper>s:minimize-when-unfocused:isolate-workspace,gnome-control-center,org.gnome.Settings,
<Hyper>v:minimize-when-unfocused:isolate-workspace,code,Code,
<Hyper>t:minimize-when-unfocused:isolate-workspace,kitty,kitty,
<Hyper>m:minimize-when-unfocused:isolate-workspace,caprine,,
<Hyper>i:minimize-when-unfocused:isolate-workspace,discord,discord,
<Hyper><Shift>b:minimize-when-unfocused:isolate-workspace,gnome-boxes,org.gnome.Boxes,
<Hyper><Shift>t:minimize-when-unfocused:isolate-workspace,telegram-desktop,org.telegram.desktop,
<Hyper><Shift>e:minimize-when-unfocused:isolate-workspace,extension-manager,com.mattjakeman.ExtensionManager,

<Hyper>g:minimize-when-unfocused:isolate-workspace,gemini.desktop,,Google Gemini
<Hyper><Shift>m:minimize-when-unfocused:isolate-workspace,mail.desktop,,Gmail
<Hyper>d:minimize-when-unfocused:isolate-workspace,deepseek.desktop,,DeepSeek - Into the Unknown
<Hyper>y:minimize-when-unfocused:isolate-workspace,youtube.desktop,,YouTube