# linux alt+F2 lg
<Hyper>b:minimize-when-unfocused:isolate-workspace,brave,brave-browser,
<Hyper>c:minimize-when-unfocused:isolate-workspace,google-chrome-stable,Google-chrome,
<Hyper>f:minimize-when-unfocused:isolate-workspace,nautilus,org.gnome.Nautilus,
<Super>f:minimize-when-unfocused:isolate-workspace,firefox,,
<Hyper>n:minimize-when-unfocused:isolate-workspace,standardnotes,,Standard Notes
<Hyper>j:minimize-when-unfocused:isolate-workspace,joplin-desktop,Joplin,
<Hyper>s:minimize-when-unfocused:isolate-workspace,gnome-control-center,org.gnome.Settings,
<Hyper>v:minimize-when-unfocused:isolate-workspace,code,Code,
<Hyper>t:minimize-when-unfocused:isolate-workspace,kitty,kitty,
<Hyper>e:minimize-when-unfocused:isolate-workspace,microsoft-edge,,
<Hyper>m:minimize-when-unfocused:isolate-workspace,caprine,,

<Hyper><Shift>d:minimize-when-unfocused:isolate-workspace,discord,,Discord
<Hyper><Shift>n:minimize-when-unfocused:isolate-workspace,notion,notion,
<Hyper><Shift>t:minimize-when-unfocused:isolate-workspace,telegram-desktop,org.telegram.desktop,
<Hyper><Shift>e:minimize-when-unfocused:isolate-workspace,extension-manager,com.mattjakeman.ExtensionManager,

<Hyper>g:minimize-when-unfocused:isolate-workspace,gemini.desktop,brave-gemini.google.com__app-Default,
<Hyper>d:minimize-when-unfocused:isolate-workspace,deepseek.desktop,brave-chat.deepseek.com__-Default,
<Hyper>y:minimize-when-unfocused:isolate-workspace,youtube.desktop,,YouTube