vim = vim

vim.pack.add({ { src = "https://github.com/catppuccin/nvim" } }, { load = true })
vim.cmd.colorscheme("catppuccin")
vim.pack.add({ { src = "https://github.com/nvim-tree/nvim-web-devicons" } }, { load = true })
require("nvim-web-devicons").setup({})
vim.pack.add({ { src = "https://github.com/nvim-lua/plenary.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/MunifTanjim/nui.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-treesitter/nvim-treesitter" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects" } }, { load = true })
vim.pack.add({ { src = "https://github.com/rafamadriz/friendly-snippets" } }, { load = true })
vim.pack.add({ { src = "https://github.com/L3MON4D3/LuaSnip" } }, { load = true })
require("luasnip.loaders.from_vscode").lazy_load()
vim.pack.add({ { src = "https://github.com/hrsh7th/cmp-nvim-lsp" } }, { load = true })
vim.pack.add({ { src = "https://github.com/hrsh7th/cmp-buffer" } }, { load = true })
vim.pack.add({ { src = "https://github.com/hrsh7th/cmp-path" } }, { load = true })
vim.pack.add({ { src = "https://github.com/hrsh7th/cmp-cmdline" } }, { load = true })
vim.pack.add({ { src = "https://github.com/saadparwaiz1/cmp_luasnip" } }, { load = true })
vim.pack.add({ { src = "https://github.com/hrsh7th/nvim-cmp" } }, { load = true })
vim.pack.add({ { src = "https://github.com/zbirenbaum/copilot.lua" } }, { load = true })
vim.pack.add({ { src = "https://github.com/CopilotC-Nvim/CopilotChat.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-telescope/telescope-ui-select.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-telescope/telescope-frecency.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-telescope/telescope-file-browser.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-telescope/telescope.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/stevearc/conform.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/folke/flash.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-neo-tree/neo-tree.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/christoomey/vim-tmux-navigator" } }, { load = true })
vim.pack.add({ { src = "https://github.com/lewis6991/gitsigns.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/kylechui/nvim-surround" } }, { load = true })
vim.pack.add({ { src = "https://github.com/JoosepAlviste/nvim-ts-context-commentstring" } }, { load = true })
vim.pack.add({ { src = "https://github.com/numToStr/Comment.nvim" } }, { load = true })
require("Comment").setup({
	pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
})
vim.pack.add({ { src = "https://github.com/windwp/nvim-autopairs" } }, { load = true })
require("nvim-autopairs").setup({})
vim.pack.add({ { src = "https://github.com/mg979/vim-visual-multi" } }, { load = true })
vim.pack.add({ { src = "https://github.com/okuuva/auto-save.nvim" } }, { load = true })
require("auto-save").setup({})
vim.pack.add({ { src = "https://github.com/akinsho/toggleterm.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/nvim-lualine/lualine.nvim" } }, { load = true })
require("lualine").setup({})
vim.pack.add({ { src = "https://github.com/SmiteshP/nvim-navic" } }, { load = true })
require("nvim-navic").setup({ lsp = { auto_attach = true } })
vim.pack.add({ { src = "https://github.com/utilyre/barbecue.nvim" } }, { load = true })
require("barbecue").setup({})
vim.pack.add({ { src = "https://github.com/nvimdev/dashboard-nvim" } }, { load = true })
require("dashboard").setup({})
vim.pack.add({ { src = "https://github.com/folke/noice.nvim" } }, { load = true })
require("noice").setup({})
vim.pack.add({ { src = "https://github.com/catgoose/nvim-colorizer.lua" } }, { load = true })
require("colorizer").setup({})
vim.pack.add({ { src = "https://github.com/folke/which-key.nvim" } }, { load = true })
require("which-key").setup({})
vim.pack.add({ { src = "https://github.com/rcarriga/nvim-notify" } }, { load = true })
vim.pack.add({ { src = "https://github.com/xiyaowong/transparent.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/folke/todo-comments.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/MeanderingProgrammer/render-markdown.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/HakonHarnes/img-clip.nvim" } }, { load = true })
vim.pack.add({ { src = "https://github.com/tpope/vim-obsession" } }, { load = true })
vim.pack.add({ { src = "https://github.com/tpope/vim-dadbod" } }, { load = true })
vim.pack.add({ { src = "https://github.com/kristijanhusak/vim-dadbod-ui" } }, { load = true })
vim.pack.add({ { src = "https://github.com/kristijanhusak/vim-dadbod-completion" } }, { load = true })

require("plugins")
