---
- name: server
  hosts: localhost
  connection: local
  become: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_facts['env']['SUDO_USER'] }}"
        docker_install_compose: true
        docker_install_compose_plugin: true
  tasks:

    # --- Install apt packages ---
    - name: Install individual apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: yes
      loop:
        - vim
        - kitty
        - i3
