# Config only -- apply.ps1 does NOT install the binary, because herdr self-updates
# from its own feed and a second installer writing the same path would be two
# updaters racing. (The nix hosts are the opposite: pkgs.herdr owns the binary, so
# `herdr update` is given up -- a read-only store path cannot be replaced.)
#
# First install on a fresh machine; Windows is PREVIEW-ONLY, `-Channel stable` errors:
#   $env:HERDR_CHANNEL='preview'; irm https://herdr.dev/install.ps1 | iex
#
# `herdr --remote macmini` does NOT work from Windows and no version bump fixes it --
# upstream excludes it from the beta. Use `ssh macmini` then `herdr` there. Protocol
# numbers never come into it on this platform. What that shape loses is pasting a
# screenshot into an agent, which ahk\ferry.ahk fills instead.
#
# No ARM64 Windows build exists: install.ps1 maps Arm64 to x86_64, so on a14 herdr
# runs under Prism -- deliberate, same trade-off as kanata and rustup.
@{
    Description = 'herdr: config.toml generated from the shared file plus a Windows-only default_shell'
    Apply = {
        param($Ctx)

        $srcDir = Join-Path $Ctx.HomeManagerDir 'programs\herdr\herdr.d'
        $src    = Join-Path $srcDir 'config.toml'
        $dstDir = Join-Path $env:APPDATA 'herdr'
        $dst    = Join-Path $dstDir 'config.toml'

        if (-not (Test-Path -LiteralPath $src)) {
            Write-Warn "herdr -> shared config missing: $src"
            return
        }

        # Generated, not linked, unlike every other entry here: herdr reads exactly ONE
        # config file, and `default_shell` differs per OS. Empty is not neutral on
        # Windows -- herdr spawns PowerShell 5.1, which reads a different profile
        # directory than the one dotfiles.pwsh links, so the pane comes up with no
        # profile while every log line says success. The Windows build ignores $SHELL
        # (measured), so this config value is the only lever.
        #
        # The cost: a copy means editing the shared config does not reach Windows until
        # apply.ps1 runs again, then `herdr server reload-config`. Cheaper than a second
        # checked-in config.toml, which drifts the first time a mac keybinding changes.
        $pwshExe = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
        if (-not $pwshExe) {
            Write-Warn 'herdr -> pwsh not on PATH; skipping (packages.pwsh installs it)'
            return
        }
        # Resolved at apply time so it survives pwsh moving.
        if ($pwshExe.Contains("'")) {
            Write-Warn "herdr -> pwsh path contains a quote, cannot express as a TOML literal: $pwshExe"
            return
        }

        # Inject INTO the existing [terminal] table. A second [terminal] at the end looks
        # harmless but TOML forbids redefining a table, so herdr rejects the file and
        # falls back to defaults -- exactly the bug being fixed. A duplicate key inside
        # one table is equally fatal, so an existing line is replaced.
        $lines    = Get-Content -LiteralPath $src
        $out      = [System.Collections.Generic.List[string]]::new()
        $inTerm   = $false
        $injected = $false
        $shellLine = "default_shell = '$pwshExe'"

        foreach ($line in $lines) {
            $trimmed = $line.Trim()

            # Leaving [terminal] without having injected: do it now, inside the table.
            if ($inTerm -and $trimmed.StartsWith('[') -and $trimmed -ne '[terminal]') {
                if (-not $injected) { $out.Add($shellLine); $injected = $true }
                $inTerm = $false
            }

            if ($trimmed -eq '[terminal]') {
                $out.Add($line)
                $out.Add($shellLine)
                $inTerm   = $true
                $injected = $true
                continue
            }

            # Ours wins on Windows, and two keys would be invalid TOML.
            if ($inTerm -and $trimmed -match '^default_shell\s*=') { continue }

            $out.Add($line)
        }
        if ($inTerm -and -not $injected) { $out.Add($shellLine) }

        if (-not $injected) {
            Write-Warn "herdr -> no [terminal] table in $src; not generating"
            return
        }

        $header = @(
            '# GENERATED by windows/modules/programs/herdr -- do not edit this copy.'
            '# Source: home-manager/programs/herdr/herdr.d/config.toml'
            '# The only Windows delta is default_shell; see the module for why.'
            ''
        )
        $generated = (($header + $out) -join "`r`n") + "`r`n"

        if (-not (Test-Path -LiteralPath $dstDir)) {
            New-Item -ItemType Directory -Path $dstDir -Force | Out-Null
        }

        # An older revision linked this to the shared file. The link must go BEFORE any
        # write: Set-Content follows a symlink and writes the TARGET, which would push
        # this Windows-only default_shell into the file every other host reads.
        if (Test-Path -LiteralPath $dst) {
            $item = Get-Item -LiteralPath $dst -Force
            if ($item.LinkType -in 'SymbolicLink', 'Junction') {
                Remove-Item -LiteralPath $dst -Force
                Write-Info 'herdr -> replaced the old symlink with a generated file'
            }
        }

        $current = if (Test-Path -LiteralPath $dst) {
            Get-Content -LiteralPath $dst -Raw -ErrorAction SilentlyContinue
        } else { $null }

        if ($current -eq $generated) {
            Write-Skip "$dst"
        } else {
            Set-Content -LiteralPath $dst -Value $generated -NoNewline -Encoding utf8
            Write-OK "$dst  (default_shell = $pwshExe)"
            Write-Info 'herdr -> run `herdr server reload-config` to apply without restarting'
        }

        # No platform delta, so a real link keeps the live-edit property. Individual
        # file, never the whole directory -- the running server keeps its socket, session
        # state and logs in there.
        $detection = Join-Path $srcDir 'agent-detection\claude.toml'
        if (Test-Path -LiteralPath $detection) {
            New-IdempotentSymlink -Source $detection `
                -Target (Join-Path $dstDir 'agent-detection\claude.toml') | Out-Null
        }
    }
}
