# Volume control
set $dunstify-volume dunstify -r 999 "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
bindsym XF86AudioRaiseVolume exec --no-startup-id wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+ && $dunstify-volume
bindsym XF86AudioLowerVolume exec --no-startup-id wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%- && $dunstify-volume
bindsym XF86AudioMute exec --no-startup-id wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && $dunstify-volume
   
# Microphone mute
set $dunstify-microphone dunstify -r 999 "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"
bindsym XF86AudioMicMute exec --no-startup-id wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && $dunstify-microphone

# Brightness control
set $dunstify-brightness dunstify -r 999 "$(brightnessctl -m)"
bindsym XF86MonBrightnessUp exec brightnessctl set 10%+ && $dunstify-brightness
bindsym XF86MonBrightnessDown exec brightnessctl set 10%- && $dunstify-brightness

# Screenshot 
bindsym Print exec --no-startup-id "maim -s | xclip -selection clipboard -t image/png"
bindsym $tab+grave exec --no-startup-id "maim -s | xclip -selection clipboard -t image/png"

# Battery
bindsym $tab+p exec --no-startup-id dunstify -r 999 "$(acpi -b)"

# Time
bindsym $tab+t exec --no-startup-id dunstify -r 999 "$(date +'%H:%M:%S - %d/%m/%Y')"

# keyboard repeat rate and delay
# Trackpad not config in i3wm
exec --no-startup-id xset r rate 200 30
