bindsym $mod+Return exec --no-startup-id kitty

set $focus exec --no-startup-id ~/.config/i3/scripts/i3-focus.sh
# TODO: more intelligent way to toggle window floating/tiled
set $toggle exec --no-startup-id ~/.config/i3/scripts/i3-toggle.sh

# Kitty
bindsym $cap+space $focus "kitty" "kitty"
# Brave
bindsym $cap+b $focus "brave-browser" "brave"
# Web Apps
bindsym $cap+g       $focus "gemini.google.com" "brave --app=https://gemini.google.com"
bindsym $cap+c       $focus "claude.ai__new" "brave --app=https://claude.ai/new"
bindsym $cap+k       $focus "keep.google.com" "brave --app=https://keep.google.com"
bindsym $cap+y       $focus "www.youtube.com" "brave --app=https://www.youtube.com"
bindsym $cap+shift+d $focus "chat.deepseek.com" "brave --app=https://chat.deepseek.com"
bindsym $cap+shift+m $focus "mail.google.com" "brave --app=https://mail.google.com/"
bindsym $cap+shift+n $focus "www.notion.so" "brave --app=https://www.notion.so/"
bindsym $cap+d       $focus "discord.com__app" "brave --app=https://discord.com/app"
# bindsym $cap+m       $focus "www.messenger.com" "brave --app=https://www.messenger.com"
bindsym $cap+m       $focus "www.facebook.com__messages" "brave --app=https://www.facebook.com/messages"
bindsym $cap+t       $focus "web.telegram.org" "brave --app=https://web.telegram.org"

focus_on_window_activation focus
