bindsym $mod+Return exec --no-startup-id kitty 
# bindsym $cap+space exec --no-startup-id $run 'class = "kitty"' kitty
# bindsym $cap+space exec --no-startup-id raiseorlaunch -e kitty -s kitty -w kitty
# bindsym $cap+b exec --no-startup-id raiseorlaunch -e "brave" -s brave-browser -w brave
# bindsym $cap+g exec --no-startup-id raiseorlaunch -e "brave --app=https://gemini.google.com" -s "gemini.google.com" -w gemini
# bindsym $cap+k exec --no-startup-id raiseorlaunch -e "brave --app=https://keep.google.com" -s "keep.google.com" -w keep
# bindsym $cap+y exec --no-startup-id raiseorlaunch -e "brave --app=https://www.youtube.com" -s "www.youtube.com" -w youtube
# bindsym $cap+shift+d exec --no-startup-id raiseorlaunch -e "brave --app=https://chat.deepseek.com" -s "chat.deepseek.com" -w deepseek
# bindsym $cap+shift+m exec --no-startup-id raiseorlaunch -e "brave --app=https://mail.google.com/" -s "mail.google.com" -w mail 
# bindsym $cap+shift+n exec --no-startup-id raiseorlaunch -e "brave --app=https://www.notion.so/" -s "www.notion.so" -w notion 
# bindsym $cap+q exec --no-startup-id raiseorlaunch -e qutebrowser  -s qutebrowser -w qute
# bindsym $cap+m exec --no-startup-id raiseorlaunch -e caprine -s caprine -w caprine
# bindsym $cap+v exec --no-startup-id raiseorlaunch -e code -s code -w code 
# bindsym $cap+d exec --no-startup-id raiseorlaunch -e discord -s discord -w discord 
# # bindsym $cap+f exec --no-startup-id raiseorlaunch -e nemo -s nemo
# bindsym $cap+f exec --no-startup-id "kitty -e yazi" 
# bindsym $cap+x exec --no-startup-id raiseorlaunch -e Telegram -s Telegram -w telegram


# Kitty
bindsym $cap+space exec --no-startup-id i3-msg [instance="^kitty$"] focus || kitty
# Brave
bindsym $cap+b exec --no-startup-id i3-msg [instance="^brave-browser$"] focus || brave
# Gemini
bindsym $cap+g exec --no-startup-id i3-msg [instance="^gemini.google.com$"] focus || brave --app=https://gemini.google.com 
# GoogleKeep
bindsym $cap+k exec --no-startup-id i3-msg [instance="^keep.google.com$"] focus || brave --app=https://keep.google.com 
# YouTube
bindsym $cap+y exec --no-startup-id i3-msg [instance="^www.youtube.com$"] focus || brave --app=https://www.youtube.com
# DeepSeek
bindsym $cap+shift+d exec --no-startup-id i3-msg [instance="^chat.deepseek.com$"] focus || brave --app=https://chat.deepseek.com
# Gmail
bindsym $cap+shift+m exec --no-startup-id i3-msg [instance="^mail.google.com$"] focus || brave --app=https://mail.google.com/
# Notion
bindsym $cap+shift+n exec --no-startup-id i3-msg [instance="^www.notion.so$"] focus || brave --app=https://www.notion.so/
# Discord
bindsym $cap+d exec --no-startup-id i3-msg [instance="^discord.com__app$"] focus || brave --app=https://discord.com/app
# Messenger
bindsym $cap+m exec --no-startup-id i3-msg [instance="^www.messenger.com$"] focus || brave --app=https://www.messenger.com
# Telegram
bindsym $cap+t exec --no-startup-id i3-msg [instance="^web.telegram.org$"] focus || brave --app=https://web.telegram.org

bindsyn $cap+x exec i3-msg focus_last

# for_window [instance="^brave-browser$"] move to workspace 2
# for_window [instance="^discord.com__app$"] move to workspace 3
focus_on_window_activation focus
