# Lockscreen
bindsym $mod+$alt+l exec i3lock

# Exit i3 session
bindsym $mod+$alt+Shift+l exec "zenity --question --text='Exit i3 session?' --title='Confirmation' && i3-msg exit"

# Reboot
bindsym $mod+$alt+Shift+r exec "zenity --question --text='Reboot the system?' --title='Confirmation' && systemctl reboot"

# Poweroff
bindsym $mod+$alt+Shift+s exec "zenity --question --text='Power off the system?' --title='Confirmation' && systemctl poweroff"

# Hibernate
bindsym $mod+$alt+Shift+h exec "zenity --question --text='Hibernate the system?' --title='Confirmation' && systemctl hibernate"
