# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

bindsym $mod+q kill

bindsym $mod+Tab workspace back_and_forth

# clipboard manager
bindsym $alt+v exec --no-startup-id "CM_LAUNCHER=rofi clipmenu"
bindsym $cap+1 exec --no-startup-id xclip -selection primary -o > /tmp/clipboard_1
bindsym $tab+1 exec --no-startup-id xclip -selection c -i /tmp/clipboard_1 
bindsym $cap+2 exec --no-startup-id xclip -selection primary -o > /tmp/clipboard_2
bindsym $tab+2 exec --no-startup-id xclip -selection c -i /tmp/clipboard_2
bindsym $cap+3 exec --no-startup-id xclip -selection primary -o > /tmp/clipboard_3
bindsym $tab+3 exec --no-startup-id xclip -selection c -i /tmp/clipboard_3
bindsym $cap+4 exec --no-startup-id xclip -selection primary -o > /tmp/clipboard_4
bindsym $tab+4 exec --no-startup-id xclip -selection c -i /tmp/clipboard_4

# change focus
# bindsym $mod+h focus left
# bindsym $mod+j focus down
# bindsym $mod+k focus up
# bindsym $mod+l focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# bindsym $mod+Shift+j move left
# bindsym $mod+Shift+k move down
# bindsym $mod+Shift+l move up
# bindsym $mod+Shift+semicolon move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# bindsym $alt+h split h
# bindsym $alt+v split v
bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+t floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"

bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4

bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4


# reload the configuration file
bindsym $mod+Shift+c exec i3-msg reload && dunstify -r 999 "i3WM" "Configuration reloaded successfully!"
bindsym $mod+Shift+r restart
bindsym $tab+r restart

# resize window (you can also use the mouse for that)
mode "resize" {
    bindsym j resize shrink width 10 px or 10 ppt
    bindsym k resize grow height 10 px or 10 ppt
    bindsym l resize shrink height 10 px or 10 ppt
    bindsym semicolon resize grow width 10 px or 10 ppt

    bindsym Left resize shrink width 10 px or 10 ppt
    bindsym Down resize grow height 10 px or 10 ppt
    bindsym Up resize shrink height 10 px or 10 ppt
    bindsym Right resize grow width 10 px or 10 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"


