# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet
exec --no-startup-id picom -b

# notification
exec --no-startup-id dunst

# background
exec_always --no-startup-id sh -c "sleep 0.5 && feh --bg-fill ~/.nix/home-manager/dotfiles/images/nix-waifu.png"

# monitor
exec_always --no-startup-id autorandr --change

# clipboard
exec --no-startup-id clipmenud

# start rofi
bindsym $mod+d exec --no-startup-id rofi -show drun
bindsym $mod+space exec --no-startup-id rofi -show combi
bindsym $alt+Tab exec --no-startup-id rofi -show window

exec --no-startup-id autotiling

# https://github.com/Cretezy/i3-back
exec --no-startup-id i3-back

# vietnamese input
exec --no-startup-id fcitx5 -rd
