---
- name: Ubuntu Install
  hosts: local
  become: yes
  tasks:
    # --- Add all repositories and GPG keys ---
    - name: Add IBus Bamboo PPA
      ansible.builtin.apt_repository:
        repo: 'ppa:bamboo-engine/ibus-bamboo'
        state: present

    - name: Add Brave Browser GPG key
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'

    - name: Add Brave Browser APT source file
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
        dest: /etc/apt/sources.list.d/brave-browser-release.sources
        mode: '0644'

    - name: Add Visual Studio Code GPG key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/trusted.gpg.d/microsoft.asc
        mode: '0644'

    - name: Add Visual Studio Code APT repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: present
        filename: vscode

    - name: Add Google Chrome GPG key
      ansible.builtin.apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome APT repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main'
        state: present
        filename: google-chrome

    # --- Update the APT cache  ---
    - name: Update apt cache 
      ansible.builtin.apt:
        update_cache: yes

    # --- Install apt packages ---
    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - kitty
          - ibus
          - ibus-bamboo
          - brave-browser
          - code
          - qutebrowser
          - google-chrome-stable
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
        install_recommends: yes

    # --- Install Snap packages ---
    - name: Install Snap packages
      community.general.snap:
        name:
          - vlc
          - discord
          - telegram-desktop
          - caprine
          - localsend
        state: present

    # --- Flatpak packages ---
    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Install Flatpak applications 
      community.general.flatpak:
        name:
          - net.lutris.Lutris
        state: present
    
    # --- Other tasks ---
    - name: Create symlink for 'brave' command
      ansible.builtin.file:
        src: /usr/bin/brave-browser
        dest: /usr/bin/brave
        state: link
        force: yes