---
- name: Ubuntu Install
  hosts: local
  become: yes
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_env.SUDO_USER }}"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_env.SUDO_USER }}"
          visual_studio_code_extensions:
            - ms-python.python
            - catppuccin.catppuccin-vsc
            - vscodevim.vim
            - esbenp.prettier-vscode
            - pkief.material-icon-theme
  tasks:
    # --- Add all repositories and GPG keys ---
    - name: Add multiple PPAs
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:bamboo-engine/ibus-bamboo
        - ppa:keyd-team/ppa

    - name: Add  GPG key and APT source file
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        # Brave Browser
        - url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
          dest: '/usr/share/keyrings/brave-browser-archive-keyring.gpg'
        - url: 'https://brave-browser-apt-release.s3.brave.com/brave-browser.sources'
          dest: '/etc/apt/sources.list.d/brave-browser-release.sources'
        # Tailscale 
        - url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
          dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        - url: https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list
          dest: /etc/apt/sources.list.d/tailscale.list 
    
    - name: visudo configuration
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/90-{{ ansible_env.SUDO_USER }}
        state: present
        line: "{{ ansible_env.SUDO_USER }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        create: true
        validate: '/usr/sbin/visudo -cf %s'


    # --- Update the APT cache  ---
    - name: Update apt cache 
      ansible.builtin.apt:
        update_cache: yes

    # --- Install apt packages ---
    - name: Install individual apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: yes
      loop:
        - kitty
        - ibus
        - ibus-bamboo
        - brave-browser
        - qutebrowser
        - flatpak
        - gnome-software-plugin-flatpak
        - tailscale
        - keyd

    # --- Other tasks ---
    - name: Create symlink for 'brave' command
      ansible.builtin.file:
        src: /usr/bin/brave-browser
        dest: /usr/bin/brave
        state: link
        force: yes

    - name:  Configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
        directory_mode: '0755'
      loop:
        - src: keyd.conf
          dest: /etc/keyd/default.conf

    - name: Enabled and start services 
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - keyd

    # --- Flatpak packages ---
    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present

    - name: Install Flatpak applications
      community.general.flatpak:
        name: "{{ item }}"
        state: present
      loop:
        - org.videolan.VLC
        - com.discordapp.Discord
        - org.telegram.desktop
        - com.sindresorhus.Caprine
        - org.localsend.localsend_app
    