[mgr]
show_hidden = true

# [openers]
# video = [
#     { run = "vlc \"$@\"", desc = "Open in VLC" }
# ]

[opener]
edit = [
  { run = 'nvim %*',    block = true, desc = "nvim",           for = "windows" },
]
